### ISSUE TITLE
Undefined index: eventNumber

### ISSUE THREAD

**Issue by enumag** [prooph/event-store-http-client#16] opened 2019-01-03 10:56 UTC
Encountered this error [here](https://github.com/prooph/event-store-http-client/blob/7fe5363d74ad6a3ad204f22a6f60edc010ecfcc3/src/Internal/EventStoreHttpConnection.php#L494).

Not sure what is correct here. I'm guessing it should be `$json['positionEventNumber']` or `$entry['eventNumber']`, not sure which.

**Comment by prolic** [comment] 2019-01-03 11:07
Duplicate of https://github.com/prooph/event-store-http-client/issues/14

**Closed by prolic** 2019-01-03 11:07 UTC
